### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by Re3ker** [MozMorris/slim-skeleton#1]
first: Thank you for publishing it.

I tried to use ur repo., because I had problems with using .htaccess to set the public dir.
But there is still a problem.

my structure is the same like in ur repository, but when I access 127.0.0.1 I get the slim 404 error message.
on 127.0.0.1/public it works well.

even if I use ur repo and place the vendor in it. 
hope u can help me with my issue.

sincerely, re3ker.

**Comment by mozmorris** [comment]
Hey @Re3ker 

You're using Apache right? Can I see you Apache config for the application?

**Comment by Re3ker** [comment]
did'nt setup any extras for this application. Mod Rewrite is on. The Same Problem happens on my domain. http://re3ker.de/miod/public/ <-- accessable, what should be http://re3ker.de/miod/ <- which gives me 404.

.htaccess in http://re3ker.de/miod/

RewriteEngine on
RewriteRule ^$ public/ [L]
RewriteRule (.*) public/$1 [L]

.htaccess in http://re3ker.de/miod/public/

RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]

**Comment by mozmorris** [comment]
@Re3ker the problem is you have `/miod/` in your path. Slim is trying to find a route at `/miod/` but you probably haven't defined one.

**Comment by Re3ker** [comment]
Yeah, but this is the root (or.. shall act like the root dir.)

uploaded my skeleton (first repo, looks strange) https://github.com/Re3ker/miod

**Comment by mozmorris** [comment]
Hey @Re3ker this is unrelated to this repos since you're using the standard version of Slim https://github.com/Re3ker/miod/blob/master/composer.json#L3

You should seek help on Stackoverflow or Slim's help forum.
